Repository dudxor4587/project, pull requests merged in 2023-11, with the labels that each got.

#19 loginPage Style edit
  loginPage.css
  loginPage.html
Labels: front-end

#20 SigninPage Style edit
  loginPage.css
  loginPage.html
  signinPage.css
  signinPage.html
  signinPage.js
Labels: front-end

#21 back-end base code
  .DS_Store
  getAlarm.php
  getProducts.php
  getSales.php
  loginPage.css
  mainPage(login).css
  mainPage(login).html
  mainPage(login).js
  mainPage.css
  mainPage.html
  mainPage.js
  myPage.css
  myPage.html
  myPage.js
  productImages/.DS_Store
  productImages/66.png
  productImages/67.png
  productImages/68.png
  productImages/69.png
  productImages/70.png
  productImages/71.png
  productImages/96.png
  productImages/97.png
  productImages/rladudxor.png
  productImages/rladudxor123.png
  productView.php
  sale.php
  salePage.html
  salePage.js
  search.php
  updateCheck.php
  userImages/rladudxor123.png
Labels: back-end

#23 create adminPage
  .DS_Store
  adminPage.css
  adminPage.html
  adminPage.js
  deleteUserData.php
  fetchUserTableData.php
  login.php
  loginPage.html
  productImages/.DS_Store
  productImages/20.png
  productImages/66.png
  productImages/67.png
  productImages/68.png
  productImages/69.png
  productImages/70.png
  productImages/71.png
  productImages/96.png
  productImages/97.png
  productImages/rladudxor.png
  productImages/rladudxor123.png
  reload.php
  sale.php
  signinPage.js
Labels: back-end

#24 confirmPage Style edit
  confirmPage.css
  confirmPage.html
  infoPage.css
Labels: front-end

#25 back-end
  alarm.css
  alarm.html
  alarm.js
  check_sale_info.php
  getInterest.php
  getProducts.php
  getSales.php
  get_sale_info.php
  infoPage(sale).css
  infoPage(sale).html
  infoPage(sale).js
  infoPage.css
  infoPage.html
  infoPage.js
  like.php
  mainPage(login).css
  mainPage(login).js
  mainPage.css
  mainPage.js
  myPage.css
  myPage.html
  myPage.js
  productImages/133.png
  productImages/134.png
  productImages/135.png
  productImages/136.png
  productImages/137.png
  productImages/138.png
  productImages/139.png
  productView.php
  reload.php
  sale.php
  salePage.html
  search.php
Labels: back-end

#29 salePage Style edit
  infoPage(sale).css
  infoPage(sale).html
  infoPage.css
  infoPage.html
  salePage.css
  salePage.html
Labels: front-end

#30 back-end
  check_sale_info.php
  logout.php
  mainPage(login).js
  myPage.js
  salePage.js
Labels: back-end

#32 back-end
  check_sale_info.php
  get_sale_info.php
  get_writer_info.php
  infoPage(sale).css
  infoPage(sale).html
  infoPage(sale).js
  infoPage.css
  infoPage.html
  infoPage.js
  like.php
  mainPage.js
  save_comment.php
  userImages/rladudxor1234.png
Labels: bug, back-end

#33 back-end infoPage
  infoPage(sale).css
  infoPage(sale).html
  infoPage(sale).js
  infoPage.css
  infoPage.html
  infoPage.js
  productImages/140.png
  productImages/141.png
Labels: back-end

#34 mainPage Style edit
  infoPage.html
  mainPage(login).css
  mainPage(login).html
  mainPage.css
  mainPage.html
  signinPage.html
Labels: front-end

#39 login, logo click event
  confirmPage.html
  confirmPage.js
  infoPage(logout).html
  infoPage(logout).js
  infoPage(sale).html
  infoPage(sale).js
  infoPage.html
  infoPage.js
  login.php
  loginPage.html
  loginPage.js
  mainPage(login).html
  mainPage(login).js
  mainPage.html
  mainPage.js
  salePage.html
  salePage.js
  signinPage.html
  signinPage.js
Labels: back-end

#44 back-end
  deleteUserData.php
  get_sale_info.php
  infoPage(logout).js
  infoPage(sale).css
  infoPage(sale).js
  infoPage.css
  infoPage.js
  login.php
Labels: back-end

#45 adminPage, requestPage Style edit
  adminPage.css
  adminPage.html
  mainPage(login).css
  mainPage.css
  myPage.css
  myPage.html
  requestPage.css
  requestPage.html
Labels: front-end

#46 bug fix
  myPage.css
  myPage.html
  myPage.js
  productImages/147.png
  productImages/148.png
  userImages/rladudxor.png
Labels: bug, front-end

#47 back-end done
  confirm.php
  confirmPage.css
  confirmPage.js
  confirmPurchase.php
  deleteKeyword.php
  getProducts.php
  infoPage(sale).css
  infoPage.css
  mainPage(login).css
  myPage.css
  myPage.js
  productImages/149.png
  productImages/150.png
  productImages/151.png
  request.php
  requestPage.css
  requestPage.html
  requestPage.js
  salePage.css
  salePage.html
  salePage.js
  search.php
Labels: back-end
